[package]
name = "git-absorb"
version = "0.6.1"

authors = ["Stephen Jung <tummychow511@gmail.com>"]
description = "git commit --fixup, but automatic"
homepage = "https://github.com/tummychow/git-absorb"
repository = "https://github.com/tummychow/git-absorb"
readme = "README.md"
license = "BSD-3-Clause"
edition = "2018"

include = [
    "**/*.rs",
    "Cargo.*",
    "*.md",
]

[[bin]]
name = "git-absorb"
path = "src/main.rs"

[dependencies.git2]
version = "~0.9"
default-features = false

[dependencies]
clap = "~2.30"
slog = "~2.5"
slog-term = "~2.5"
slog-async = "~2.5"
failure = "~0.1"
memchr = "~2.0"

[patch.crates-io]
slog-term = { git = "https://github.com/tummychow/term", branch = "fallback-no-color" }

[dev-dependencies]
tempdir = "~0.3"
