name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: git-absorb-${{ matrix.os }}
        path: |
          target/release/git-absorb
          target/release/git-absorb.exe

  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check format
        run: cargo fmt --check

  build-man-page:
    name: build-man-page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install asciidoc
      - name: Build from asciidoc
        working-directory: ./Documentation
        run: make
      - name: Upload man page as artifact
        uses: actions/upload-artifact@v4
        with:
          path: Documentation/git-absorb.1
          name: git-absorb.1
